### ISSUE TITLE
Timelines Not Created

### ISSUE THREAD

**Issue by kevincolber** [ChristyKail/resolve_auto_import#1]
OS 14.6.1
Resolve 19.1

When using the quick action the files are imported and binned correctly, however no timeline is created. Tested with Alexa 35 MXF Arriraw from one job and Mini LF ProRes from another job. Interestingly I also dont get the popup warning me resolve is changing the project frame rate to match the imported clips either. Not sure if that's related. I tried reinstalling the script.

**Comment by ChristyKail** [comment]
Hi, I've been able to replicate your issue in the latest version of the script and have just pushed a commit that fixed the problem - please redownload and see if it's resolved.

**Comment by kevincolber** [comment]
New version is working great, thanks for the quick response! Excellent tool!
