### ISSUE TITLE
Import doesn't bring in clips in sequential order

### ISSUE THREAD

**Issue by seefiggy** [ChristyKail/resolve_auto_import#2]
Hello,

Love this script. It's saved us plenty of time doing our imports into resolve for all of the camera rolls we're getting. I did have some feedback from our operator who is asking if it's at all possible to have the clips imported in proper order. If they're imported in proper order, he can speed through CDL application much quicker. If this can be implemented  that would be amazing. Again really appreciate this script. It's been great help.

**Comment by ChristyKail** [comment]
Hi there

By the proper order, do you mean sorted alphabetically by file name? I thought it already did that but I will dive into the code to check.

Cheers

**Comment by seefiggy** [comment]
Hello, Yes it looks like it imports the clips in order but when it creates the timeline, The order shifts around. Here are a couple  of screen grabs. Appreciate your help. 
![Screen Shot 2024-12-16 at 3 26 51 PM](https://github.com/user-attachments/assets/93ee0c4b-8821-4c08-a064-3645abb82b80)
![Screen Shot 2024-12-16 at 3 26 59 PM](https://github.com/user-attachments/assets/4b07138a-4022-403d-b21b-073b31fc6ab6)

**Comment by ChristyKail** [comment]
Hi
Please download the latest patch and see if this fixes the issue. I've added a function to force the clips into alphanumeric order by clip name when creating the timeline.

**Comment by seefiggy** [comment]
Thanks so much! I'll download and try it out. Much appreciated

**Comment by seefiggy** [comment]
Just wanted to update. This fix worked like a charm. Many thanks!
